### ISSUE TITLE
Exception catch trying to know if the app is in debug mode or not

### ISSUE THREAD

**Issue by pamartineza** [Karumi/FlowUpAndroidSDKIssueTracker#6] opened 2017-01-01 17:24 UTC
Hi,

I'm using FlowUp 0.2.7, and every time I run the app in debug mode I can see this Exception printed in Logcat:

```
E/FlowUp: Exception catch trying to know if the app is in debug mode or not
          java.lang.ClassNotFoundException: com.greenlionsoft.free.madrid.debug.BuildConfig
              at java.lang.Class.classForName(Native Method)
              at java.lang.Class.forName(Class.java:400)
              at java.lang.Class.forName(Class.java:326)
              at io.flowup.a.c.a(Unknown Source)
              at io.flowup.FlowUp$Builder.start(Unknown Source)
              at com.greenlionsoft.free.madrid.adapters.ApplicationAdapter.startFlowUpIfEnabled(ApplicationAdapter.java:71)
              at com.greenlionsoft.free.madrid.adapters.ApplicationAdapter.onCreate(ApplicationAdapter.java:62)
              at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
              at android.app.ActivityThread.-wrap2(ActivityThread.java)
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
              at android.os.Handler.dispatchMessage(Handler.java:102)
              at android.os.Looper.loop(Looper.java:154)
              at android.app.ActivityThread.main(ActivityThread.java:6119)
              at java.lang.reflect.Method.invoke(Native Method)
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
           Caused by: java.lang.ClassNotFoundException: Didn't find class "com.greenlionsoft.free.madrid.debug.BuildConfig" on path: DexPathList[[zip file "/data/app/com.greenlionsoft.free.madrid.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/com.greenlionsoft.free.madrid.debug-1/lib/arm64, /system/lib64, /vendor/lib64]]
              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
              at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
              at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
              at java.lang.Class.classForName(Native Method) 
              at java.lang.Class.forName(Class.java:400) 
              at java.lang.Class.forName(Class.java:326) 
              at io.flowup.a.c.a(Unknown Source) 
              at io.flowup.FlowUp$Builder.start(Unknown Source) 
              at com.greenlionsoft.free.madrid.adapters.ApplicationAdapter.startFlowUpIfEnabled(ApplicationAdapter.java:71) 
              at com.greenlionsoft.free.madrid.adapters.ApplicationAdapter.onCreate(ApplicationAdapter.java:62) 
              at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024) 
              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403) 
              at android.app.ActivityThread.-wrap2(ActivityThread.java) 
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
              at android.os.Handler.dispatchMessage(Handler.java:102) 
              at android.os.Looper.loop(Looper.java:154) 
              at android.app.ActivityThread.main(ActivityThread.java:6119) 
              at java.lang.reflect.Method.invoke(Native Method) 
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
D/FlowUp: FlowUp initialized
```

**Comment by pedrovgs** [comment] 2017-01-30 14:47
Hi @pamartineza sorry for the late response. I've just seen this issue.

Don't worry about that message. Your application configuration should be overriding the default package name that's why you see that log trace. Your app is not crashing, it's just showing that informative trace. 

This log message you see it's related to a feature we've added to double check if your app is running as debuggable or not. Don't worry, we will update the log message to just show the first line and not the whole exception. 

As this is not a bug I'm closing this issue. Thank you so much :)

**Closed by pedrovgs** 2017-01-30 14:47 UTC
